version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: projetoextensao:0.1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/backend/
    ports:
      - "8003:8000"